apiVersion: v2
name: home-assistant
description: Wrapper Helm chart for Home Assistant smart home platform
type: application
version: 1.0.0
appVersion: "2026.1.0"
dependencies:
  - name: home-assistant
    version: 0.3.41
    repository: http://pajikos.github.io/home-assistant-helm-chart/
  - name: gateway-route
    version: 1.0.0
    repository: file://../../../charts/gateway-route
  - name: mdns-config
    version: 1.0.0
    repository: file://../../../charts/mdns-config
  - name: longhorn-storage
    version: 1.0.0
    repository: file://../../../charts/longhorn-storage
