apiVersion: v1
kind: Service
metadata:
  name: coredns-tailscale
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    tailscale.com/hostname: cluster-dns
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 53
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    k8s-app: coredns
    app.kubernetes.io/name: coredns
