apiVersion: v2
name: traefik-ingress
description: Reusable Traefik IngressRoute for LAN HTTP services
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: mdns-config
    version: 1.0.0
    repository: file://../mdns-config
