namespace: kube-system

metrics-server:
  # A complete list of values can be found here:
  # https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml

  priorityClassName: "system-node-critical"

  # Skip TLS verification for kubelet - required when using Tailscale IPs
  # since kubelet certs don't include Tailscale IP SANs
  args:
    - --kubelet-insecure-tls
