apiVersion: v2
name: timemachine
description: Time Machine backup server for macOS
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: bitwarden-secret
    version: 1.0.0
    repository: file://../../../charts/bitwarden-secret
    condition: bitwarden-secret.enabled
