apiVersion: v2
name: mosquitto
description: Wrapper Helm chart for Eclipse Mosquitto MQTT broker
type: application
version: 1.0.0
appVersion: "2.0.22"
dependencies:
  - name: mosquitto
    version: 0.5.2
    repository: https://bdclark.github.io/helm-charts
