apiVersion: v2
name: mosquitto
description: Wrapper Helm chart for Eclipse Mosquitto MQTT broker
type: application
version: 1.0.0
appVersion: "2.0.22"
dependencies:
  - name: mosquitto
    version: 0.6.1
    repository: https://bdclark.github.io/helm-charts
  - name: mdns-config
    version: 1.0.0
    repository: file://../../../charts/mdns-config
