apiVersion: v2
name: gateway-route
description: Reusable HTTPRoute and ReferenceGrant resources for Gateway API
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: mdns-config
    version: 1.0.0
    repository: file://../mdns-config
