{{- $version := .Values.kubernetesVersion }}
{{- $versionSlug := $version | replace "." "-" }}
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes-upgrade-{{ $versionSlug }}
spec:
  kubernetes:
    version: {{ $version }}
