apiVersion: v2
name: external-secrets
description: Wrapper Helm chart for external-secrets
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: external-secrets
    version: 1.3.2
    repository: https://charts.external-secrets.io
