{{- if .Values.avp.enabled }}
# Allow repo-server to read secrets across namespaces for AVP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-avp-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-avp-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-avp-secret-reader
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: {{ .Release.Namespace }}
{{- end }}
