{{- if and .Values.webhook.enabled .Values.webhook.bitwardenSecretId }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: webhook.github.secret
      remoteRef:
        key: {{ .Values.webhook.bitwardenSecretId }}
{{- end }}
