apiVersion: v2
name: mdns-advertiser
description: mDNS service advertiser for LAN discovery
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: mdns-advertiser
    version: 1.0.0
    repository: file://../../../charts/mdns-advertiser
