apiVersion: v2
name: traefik
description: Wrapper Helm chart for Traefik
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: traefik
    version: 39.0.0
    repository: https://traefik.github.io/charts
