apiVersion: v2
name: traefik
description: Wrapper Helm chart for Traefik
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: traefik
    version: 34.2.0
    repository: https://traefik.github.io/charts
  - name: tailscale-ingress
    version: 1.0.0
    repository: file://../../../../charts/tailscale-ingress
    condition: tailscale-ingress.enabled
