namespace: metallb
syncWave: "-2"

# IP pool for LoadBalancer services. Customize for your network:
# - Must be in your LAN subnet
# - Must not overlap with DHCP range or other static IPs
# - These IPs are announced via ARP (Layer 2 mode)
pool:
  name: default-pool
  addresses:
    - "192.168.0.200-192.168.0.250"

advertisement:
  name: default
  ipAddressPools:
    - default-pool

metallb:
  # A complete list of values can be found here:
  # https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml

  speaker:
    frr:
      enabled: false
