apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
