apiVersion: v2
name: signoz
description: Wrapper Helm chart for SigNoz observability platform
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: signoz
    version: 0.111.0
    repository: https://charts.signoz.io
  - name: gateway-route
    version: 1.0.0
    repository: file://../../../charts/gateway-route
  - name: bitwarden-secret
    version: 1.0.0
    repository: file://../../../charts/bitwarden-secret
