apiVersion: v2
name: coredns
description: CoreDNS for wildcard DNS resolution of catfish-mountain.com
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: coredns
    version: 1.32.0
    repository: https://coredns.github.io/helm
