apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: {{ .Release.Namespace }}
      bitwardenServerSDKURL: https://bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        key: ca.crt
        namespace: {{ .Release.Namespace }}
      organizationID: {{ .Values.bitwarden.organizationID }}
      projectID: {{ .Values.bitwarden.projectID }}
