{{- if index .Values "external-secrets" "bitwarden-sdk-server" "enabled" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server
spec:
  secretName: bitwarden-tls-certs
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: RSA
    size: 4096
  dnsNames:
    - bitwarden-sdk-server
    - bitwarden-sdk-server.{{ .Release.Namespace }}
    - bitwarden-sdk-server.{{ .Release.Namespace }}.svc
    - bitwarden-sdk-server.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
{{- end }}
