apiVersion: v2
name: kube-state-metrics
description: Wrapper Helm chart for kube-state-metrics (Kubernetes object state metrics)
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-state-metrics
    version: 5.37.0
    repository: https://prometheus-community.github.io/helm-charts
