---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-catfish-mountain-com
  namespace: {{ .Values.namespace }}
spec:
  secretName: wildcard-catfish-mountain-com-tls
  duration: 87600h  # 10 years
  renewBefore: 720h  # 30 days
  commonName: "*.catfish-mountain.com"
  dnsNames:
    - "catfish-mountain.com"
    - "*.catfish-mountain.com"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
