apiVersion: v2
name: jellyfin
description: Wrapper Helm chart for Jellyfin media server with Intel QuickSync transcoding
type: application
version: 1.0.0
appVersion: "10.11.5"
dependencies:
  - name: jellyfin
    # renovate: datasource=helm registryUrl=https://jellyfin.github.io/jellyfin-helm
    version: 2.7.0
    repository: https://jellyfin.github.io/jellyfin-helm
  - name: gateway-route
    version: 1.0.0
    repository: file://../../../charts/gateway-route
  - name: mdns-config
    version: 1.0.0
    repository: file://../../../charts/mdns-config
  - name: longhorn-storage
    version: 1.0.0
    repository: file://../../../charts/longhorn-storage
