apiVersion: v2
name: jellyfin
description: Wrapper Helm chart for Jellyfin media server with Intel QuickSync transcoding
type: application
version: 1.0.0
appVersion: "10.11.5"
dependencies:
  - name: jellyfin
    # renovate: datasource=helm registryUrl=https://jellyfin.github.io/jellyfin-helm
    version: 2.7.0
    repository: https://jellyfin.github.io/jellyfin-helm
  - name: tailscale-ingress
    version: 1.0.0
    repository: file://../../../charts/tailscale-ingress
  - name: traefik-ingress
    version: 1.0.0
    repository: file://../../../charts/traefik-ingress
  - name: longhorn-storage
    version: 1.0.0
    repository: file://../../../charts/longhorn-storage
