apiVersion: v1
kind: ServiceAccount
metadata:
  name: mdns-advertiser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdns-advertiser
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mdns-advertiser
subjects:
  - kind: ServiceAccount
    name: mdns-advertiser
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: mdns-advertiser
  apiGroup: rbac.authorization.k8s.io
