apiVersion: v2
name: argocd
description: Wrapper Helm chart for ArgoCD
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: argo-cd
    version: 9.3.6
    repository: https://argoproj.github.io/argo-helm
  - name: tailscale-ingress
    version: 1.0.0
    repository: file://../../../charts/tailscale-ingress
    condition: tailscale-ingress.enabled
  - name: bitwarden-secret
    version: 1.0.0
    repository: file://../../../charts/bitwarden-secret
    condition: bitwarden-secret.enabled
