{{- range .Values.ingresses }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - {{ .entryPoint | default "web" }}
  routes:
    - match: Host(`{{ .host }}`)
      kind: Rule
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ .service.name }}
          port: {{ .service.port | default 80 }}
{{- end }}
