apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/bafulton/homelab
        revision: main
        files:
          - path: kubernetes/infra/*/values.yaml
  template:
    metadata:
      name: '{{ get . "name" | default .path.basenameNormalized }}'  # eg, "argocd" from "kubernetes/infra/argocd"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ get . "syncWave" | default "-1" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bafulton/homelab
        targetRevision: main
        path: '{{ .path.path }}'  # eg, kubernetes/infra/argocd
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ get . "namespace" | default .path.basenameNormalized }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if (get . "serverSideApply") }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- end }}
    {{- if (get . "ignoreDifferences") }}
    spec:
      ignoreDifferences:
        {{- range $diff := .ignoreDifferences }}
        - group: {{ $diff.group | default "" | quote }}
          kind: {{ $diff.kind | quote }}
          {{- if $diff.name }}
          name: {{ $diff.name | quote }}
          {{- end }}
          {{- if $diff.namespace }}
          namespace: {{ $diff.namespace | quote }}
          {{- end }}
          {{- if $diff.jsonPointers }}
          jsonPointers:
            {{- range $ptr := $diff.jsonPointers }}
            - {{ $ptr | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
    {{- end }}
