apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/bafulton/homelab
        revision: main
        files:
          - path: kubernetes/infra/*/values.yaml
  template:
    metadata:
      name: '{{ get . "name" | default .path.basenameNormalized }}'  # eg, "argocd" from "kubernetes/infra/argocd"
    spec:
      project: default
      source:
        repoURL: https://github.com/bafulton/homelab
        targetRevision: main
        path: '{{ .path.path }}'  # eg, kubernetes/infra/argocd
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ get . "namespace" | default .path.basenameNormalized }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if (get . "serverSideApply") }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{- end }}
