apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/bafulton/homelab
        revision: main
        files:
          - path: kubernetes/infra/*/values.yaml
  template:
    metadata:
      name: '{{ get . "name" | default .path.basenameNormalized }}'  # eg, "argocd" from "kubernetes/infra/argocd"
      annotations:
        argocd.argoproj.io/sync-wave: '{{ get . "syncWave" | default "0" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bafulton/homelab
        targetRevision: main
        path: '{{ .path.path }}'  # eg, kubernetes/infra/argocd
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ get . "namespace" | default .path.basenameNormalized }}'
  templatePatch: |
    {{- if (get . "useAVP") }}
    metadata:
      annotations:
        argocd-diff-preview/ignore: "true"
    {{- end }}
    spec:
      syncPolicy:
        automated:
          prune: {{ if and (get . "syncPolicy") (hasKey .syncPolicy "prune") }}{{ .syncPolicy.prune }}{{ else }}true{{ end }}
          selfHeal: {{ if and (get . "syncPolicy") (hasKey .syncPolicy "selfHeal") }}{{ .syncPolicy.selfHeal }}{{ else }}true{{ end }}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          {{- if and (get . "syncPolicy") (index .syncPolicy "serverSideApply") }}
          - ServerSideApply=true
          {{- end }}
      {{- if (get . "useAVP") }}
      source:
        plugin:
          name: argocd-vault-plugin-helm
      {{- end }}
      {{- if (get . "ignoreDifferences") }}
      ignoreDifferences:
        {{- range $diff := .ignoreDifferences }}
        - group: {{ index $diff "group" | default "" | quote }}
          kind: {{ index $diff "kind" | quote }}
          {{- if (index $diff "name") }}
          name: {{ index $diff "name" | quote }}
          {{- end }}
          {{- if (index $diff "namespace") }}
          namespace: {{ index $diff "namespace" | quote }}
          {{- end }}
          {{- if (index $diff "jsonPointers") }}
          jsonPointers:
            {{- range $ptr := (index $diff "jsonPointers") }}
            - {{ $ptr | quote }}
            {{- end }}
          {{- end }}
          {{- if (index $diff "jqPathExpressions") }}
          jqPathExpressions:
            {{- range $expr := (index $diff "jqPathExpressions") }}
            - {{ $expr | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
