apiVersion: v2
name: cert-manager
description: Wrapper Helm chart for cert-manager
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: v1.19.3
    repository: oci://quay.io/jetstack/charts
  - name: bitwarden-secret
    version: 1.0.0
    repository: file://../../../charts/bitwarden-secret
