{{- if .Values.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-lan
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.traefik.hostname }}`)
      kind: Rule
      services:
        - name: home-assistant
          port: {{ .Values.traefik.servicePort }}
{{- end }}
