apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-packages
  namespace: {{ .Release.Namespace }}
data:
  {{- range $path, $_ := .Files.Glob "files/packages/*.yaml" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
