apiVersion: v2
name: node-exporter
description: Wrapper Helm chart for prometheus-node-exporter (temperature/hardware metrics)
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus-node-exporter
    version: 4.51.0
    repository: https://prometheus-community.github.io/helm-charts
