{{- if .Values.storageClasses }}
{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  {{- if .default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: {{ .reclaimPolicy | default "Delete" }}
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "{{ .replicas | default 1 }}"
  staleReplicaTimeout: "2880"  # 48 hours
  fromBackup: ""
  fsType: "ext4"
  {{- if .diskSelector }}
  diskSelector: {{ .diskSelector | quote }}
  {{- end }}
  {{- if .nodeSelector }}
  nodeSelector: {{ .nodeSelector | quote }}
  {{- end }}
  {{- if .dataLocality }}
  dataLocality: {{ .dataLocality | quote }}
  {{- end }}
{{- end }}
{{- end }}
