apiVersion: v2
name: tailscale-operator
description: Wrapper Helm chart for tailscale-operator
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: tailscale-operator
    version: 1.92.5
    repository: https://pkgs.tailscale.com/helmcharts
  - name: bitwarden-secret
    version: 1.0.0
    repository: file://../../../charts/bitwarden-secret
    condition: bitwarden-secret.enabled
