apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: signoz-alert-sync
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: signoz-alert-sync
subjects:
  - kind: ServiceAccount
    name: signoz-dashboard-sync
    namespace: signoz
roleRef:
  kind: ClusterRole
  name: signoz-alert-sync
  apiGroup: rbac.authorization.k8s.io
