{{- range .Values.ingresses }}
{{- if .service.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  type: ClusterIP
  selector:
    {{- toYaml .service.targetSelector | nindent 4 }}
  ports:
    - name: http
      port: {{ .service.port | default 80 }}
      targetPort: {{ .service.targetPort | default 80 }}
{{- end }}
{{- end }}
